// example url:
//secure channel request
//https://example.com/api/collectionname
// /api/ is common practice for RESTful APIs

//non secure channel request
//http://example.com/api/collectionname
// notice the lack of the s in https

//Localhost

###
GET http://localhost:3000/contacts

###
GET http://localhost:3000/contacts/63328d4d94e93301d3031ada

###
GET http://localhost:3000/contacts/6332948f94e93301d3031ade

###
GET http://localhost:3000/contacts/633295c794e93301d3031adf

### Create a new contact
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Lando",
    "lastName":"Calrissian",
    "email":"lando@calrissian.com",
    "favoriteColor":"blue",
    "birthday":"1937-04-06"
}

### Update a contact
PUT http://localhost:3000/contacts/633fabf43578a74c11071a8f HTTP/1.1
content-type: application/json

{
    "firstName":"Chewbacca",
    "lastName":"Wookie",
    "email":"therealchewie@thewookie.com",
    "favoriteColor":"grey",
    "birthday":"1937-04-06"
}

### Delete a contact
DELETE http://localhost:3000/contacts/633fae1b3578a74c11071a90 HTTP/1.1

//production

###
GET https://week02personalassignment.onrender.com/contacts 

###
GET https://week02personalassignment.onrender.com/contacts/63328d4d94e93301d3031ada

### 
GET https://week02personalassignment.onrender.com/contacts/6332948f94e93301d3031ade

###
GET https://week02personalassignment.onrender.com/contacts/633295c794e93301d3031adf

### Create a new contact
POST https://week03personalassignment.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Lando",
    "lastName":"Calrissian",
    "email":"lando@calrissian.com",
    "favoriteColor":"blue",
    "birthday":"1937-04-06"
}

### Update a contact
PUT https://week03personalassignment.onrender.com/contacts/633fabf43578a74c11071a8f HTTP/1.1
content-type: application/json

{
    "firstName":"Chewbacca",
    "lastName":"Wookie",
    "email":"therealchewie@thewookie.com",
    "favoriteColor":"grey",
    "birthday":"1937-04-06"
}

### Delete a contact
DELETE https://week03personalassignment.onrender.com/contacts/633fae1b3578a74c11071a90 HTTP/1.1
